### ISSUE TITLE
Add ability to override base command

### ISSUE THREAD

**Issue by josegonzalez** [commander-cli/cmd#27]
It would be great to be able to override the base command. In my case, I'd like to have the ability to run linux commands on a remote server (via ssh) and at the moment that is not possible.

**Comment by dylanhitt** [comment]
Hello @josegonzalez 

Thank you for the issue! Providing the ability to override a base command is an excellent idea and fairly trivial at a glance. Your use case sounds interesting. At this point why use this package over the `os/exec`. Is it that you prefer this wrapper over the stdlib implementation? Apologies if I'm probing too much, I just enjoy the feedback.

Cheers!

**Comment by dylanhitt** [comment]
I performed a bit of an experiment with this https://github.com/commander-cli/cmd/pull/28

Let me know if this what you're after. I'm not quite sure if this is within the context of this package, maybe you can provide me some insight to convince me otherwise. This would make this package very flexible for most use cases. 🤷‍♂️

**Comment by josegonzalez** [comment]
I am a fan of the api you exposed around setting stdout/stderr, as well as the process management. I would rather not rewrite this in my own project just to add support for ssh-based exec.

**Comment by dylanhitt** [comment]
To give credit where credit is due @SimonBaeumer is the mastermind behind this interface 😄
